### ISSUE TITLE
PFCOUNT should accept multiple keys, not just one.

### ISSUE THREAD

**Issue by anysql** [onexsoft/OneValue#11]
redis> PFADD hll foo bar zap
(integer) 1
redis> PFADD hll zap zap zap
(integer) 0
redis> PFADD hll foo bar
(integer) 0
redis> PFCOUNT hll
(integer) 3
redis> PFADD some-other-hll 1 2 3
(integer) 1
redis> PFCOUNT hll some-other-hll
(integer) 6
redis> 

The current version just support one key for PFCOUNT command

**Comment by leviathan0992** [comment]
#12
